# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8083
    #ssl:
     # key-store: ${user.home}/keystore.p12
      #key-store-password: 123456
      #key-store-type: PKCS12
      #key-alias: tomcat
    #打开注释，则通过【http://localhost/dp-lte】访问
    #context-path: /dp-lte

spring:
    # 环境 dev:开发环境|test:测试环境|prod:生成环境
    profiles:
        active: dev
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    http:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # thymeleaf 模板引擎
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        mode: LEGACYHTML5
        encoding: UTF-8
        content-type: text/html
    resources: # 指定静态资源的路径
        static-locations: classpath:/static/,classpath:/templates/
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 1
        host: 127.0.0.1
        port: 6379
        password:       # 密码（默认为空）
        timeout: 6000  # 连接超时时长（毫秒）
        pool:
            max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
            max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
            max-idle: 10      # 连接池中的最大空闲连接
            min-idle: 5       # 连接池中的最小空闲连接
    messages:
      basename: i18n/messages

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml


#代码生成器配置:
generator:
    project:
        basePath: E:\开源程序\demo01
    basePackage:  com.demoules
    mapper:
        path: mapper
    view:
        path: templates
    js:
        path: static